config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :groups
  resources :users, only: [:index]

end

app/models/friends_group.rb
class FriendsGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  
end

app/models/friends_groups.rb
class FriendsGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :friends_groups
  has_many :users,
    through: :friends_groups

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friends_groups
  has_many :groups,
    through: :friends_groups
  validates :name, presence: true
  validates :email, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authorize_user

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted!"
    redirect_to admin_users_path
  end

  private
  def authorize_user
    if !user_signed_in? || !current_user.admin?
      flash[:errors] = "You don't have the privileges to do that!"
      redirect_to dinosaurs_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name]
    # devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    # devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
    # devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ActionController::Base

  def index
    @users = User.all
    @user = current_user
    @all_groups = Group.all
    @groups = []
    @all_groups.each do |grp|
      if grp.user_id == @user.id
        @groups << grp
      end
      @groups
    end
      @groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      flash[:notice] = "Group Added!"
      redirect_to groups_path
    else
      flash[:errors] = @group.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      flash[:success] = "Group Updated!"
      redirect_to @group
    else
      flash[:errors] = @group.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      flash[:success] = "Group Deleted!"
      redirect_to groups_path
    else
      flash[:errors] = @group.errors.full_messages.join(". ")
      redirect_to @group
    end
  end

  private

  def group_params
    params.require(:group).permit(
      :name,
      :description).merge(user_id: current_user.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/admin/users/index.html.erb
<h1>Welcome to your personal White Elephant page!</h1>
<% @users.each do |user| %>
  <div>
    <%= user.email %>
    <% if user.admin? %>
      <b>admin</b>
    <% end %>
    <%= button_to "Delete #{user.email}!", admin_user_path(user), class: "crud-buttons button expand round medium user#{user.id}", method: :delete %>
  </div>
<% end %>

app/views/groups/index.html.erb
<h1>These are all of my groups!</h1>

<% if @groups.empty? %>
  No groups yet. Go ahead, create one!
<% else %>
  <% @groups.each do |group| %>
  <h3>Group Name:
    <%= group.name %>
  </h3>
  <h4> Description : <%= group.description %> </h4>
  <p>
    Group Creator: <%= @users[group.user_id - 1].name %>
  </p>
  <% end %>
<% end %>
<p>

</p>
<%= button_to "Create a new group!", new_group_path, class: 'crud-buttons button expand round medium', method: :get %>

app/views/groups/new.html.erb
<h1 class="sub-header">Create a Group!</h1>
<h1>Because, this:</h1>
<%= image_tag "white_elephant_gift.gif" %>

<% if user_signed_in? %>
  <%= form_for(@group) do |form| %>
    <div class="field column small-12">
      <%= form.label :name, "Group Name", class: "text-input-label" %><br>
      <%= form.text_field :name, class: "text-input-field", placeholder: @group.name %>
    </div>
    <br>
    <div class="field column small-12">
      <%= form.label :description, class: "text-input-label" %><br>
      <%= form.text_field :description, class: "text-input-field", placeholder: @group.description%>
    </div>

    <br>
    <div class="actions">
      <%= form.submit "Create this Group!", class: "crud-buttons button expand round medium" %>
    </div>
  <% end %>
<% else %>
  <h3>Please <%= link_to 'Sign Up', new_user_registration_path %> or
  <%= link_to 'Sign In', new_user_session_path %></h3>
<% end %>

app/views/homes/index.html.erb
<% if user_signed_in? %>
  <%= button_to "See my groups", groups_path, method: :get %>
  <%= button_to "Create a new group!", new_group_path, method: :get %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>White Elephant</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">White Elephant Gift Exchanger</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>
  <%= image_tag "white-elephant-gift-exchange.gif" %>
    <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
<%= content_for :extra_footer do %>
  <script type="text/javascript">
    var widget = new Something.Widget('foo');
  </script>
<% end %>
</html>